#!/bin/bash

# Пути
HYPRPAPER_CONF="$HOME/.config/hypr/hyprpaper.conf"
WAL_CACHE_DIR="$HOME/.cache/wal"
HYPRLAND_COLORS="$WAL_CACHE_DIR/colors-hyprland.conf"

# Получаем текущие обои из hyprpaper.conf
WALLPAPER=$(grep -oP '^\s*wallpaper\s*=\s*.*,\s*\K[^,[:space:]]+' "$HYPRPAPER_CONF" | head -n1 | tr -d '"')

# Проверка обоев
if [ ! -f "$WALLPAPER" ]; then
    echo "Обои не найдены: '$WALLPAPER'"
    exit 1
fi

echo "Генерация палитры для: $WALLPAPER"
wal -i "$WALLPAPER" -n -q --backend schemer2

# Сохраняем Hyprland-совместимый конфиг
accent="rgb($(jq -r '.colors.color1' "$WAL_CACHE_DIR/colors.json"))"
text="rgb($(jq -r '.colors.foreground' "$WAL_CACHE_DIR/colors.json"))"
background="rgb($(jq -r '.colors.background' "$WAL_CACHE_DIR/colors.json"))"

cat > "$HYPRLAND_COLORS" <<EOF
# Autogenerated by pywal

\$accent = $accent
\$text = $text
\$background = $background

general {
    border_size = 2
    col.active_border = \$accent
    col.inactive_border = \$background
}

decoration {
    col.shadow = \$accent
    col.shadow_inactive = \$background
}
EOF

echo "Hyprland цвета сохранены"

echo "Цветовая схема успешно обновлена!"